%.class: src/%/
	@rm -rf $*
	@mkdir $*
	@javac src/$*/*.java -d .

clean:
	@rm -rf out/
	@rm -rf setup/
	@rm -rf step0_repl/
	@rm -rf step1_read_print/
	@rm -rf step2_eval/
	@rm -rf step3_env/
	@rm -rf step4_if_fn_do/
	@rm -rf step5_tco/
	@rm -rf step6_file/
